### ISSUE TITLE
Unexpected file extension for a Conda environment file

### ISSUE THREAD

**Issue by sitzbrau** [rajtilakjee/fooocus-sagemaker-studio#2]
in Sagemaker Lab after i've cloned the repository it appears this message
Unexpected file extension for a Conda environment file

Conda environment files are expected to have extensions of .yml, .yaml or .txt. The environment file provided has a different extension: sagemaker-studiolab-notebooks/fooocus-sagemaker-studio/README.md. Please check to make sure the file provided is a valid Conda environment file.

![image](https://github.com/rajtilakjee/fooocus-sagemaker-studio/assets/158448004/41c67676-c06d-47e8-9680-19297de29386)

**Comment by rajtilakjee** [comment]
Please provide more details on how you are trying to add this repository to SageMaker Studio Lab?

**Comment by sitzbrau** [comment]
i'm following the step of this tutorial
https://www.youtube.com/watch?v=rO9Jp88YFE0

**Comment by rajtilakjee** [comment]
> i'm following the step of this tutorial https://www.youtube.com/watch?v=rO9Jp88YFE0

Which GitHub repo link are you using for importing into SageMaker Studio Lab?

**Comment by sitzbrau** [comment]
sorry, my fault, i didn't disabled  **Search for environment.yml and build Conda environment.**

![image](https://github.com/rajtilakjee/fooocus-sagemaker-studio/assets/158448004/bd5c2d8f-5378-483e-ad4c-ef3758b6ef1c)
